#  REPLACING 18th QUESTION'S DOUBLE SPACE TO SINGLE SPACE AND VICE VERSA
a='THIS STATEMENT  INCLUDES DOUBLE SPACE AND  SINGLE SPACE TOO! THANKYOU FOR  DETECTING!'
b=a.replace(" ","  ")
print(b)

c=a.replace("  "," ")
print(c)