a={}
u1=input("ENTER 1 FAV LANGUAGE YUKTI ")
u2=input("ENTER 2 FAV LANGUAGE SOMI  ")
u3=input("ENTER 3 FAV LANGUAGE KRISHU ")
u4=input("ENTER 4 FAV LANGUAGE SEEMS ")
a["YUKTI"]=u1    #THIS IS THE ONLY METHOD TO ENTER KEY VALUES IN EMPTY DICT.
a["SOMI"]=u2     #IF 2 NAMES ARE SAME SO RECENTLY UPDATED VALUE WILL PRINT NOT THE PREVIOUS ONE.
a["KRISHU"]=u3 
a["SEEMS"]=u4
print(a)